//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Text
    {
        public int Id { get; set; }
        public string Id_Text { get; set; }
        public string Text1 { get; set; }
    }
}
